import { jsPDF } from "jspdf";
import { PlannerState } from "@/types/mandal";

const PURPLE = [127, 119, 221] as const;
const LIGHT_PURPLE = [206, 203, 246] as const;

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function formatDateFull(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
}

export function generateDailyPDF(state: PlannerState) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const today = todayStr();
  const pageW = 210;
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 0;

  // ─── Header ───────────────────────────────────────────
  doc.setFillColor(...PURPLE);
  doc.rect(0, 0, pageW, 36, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Planner", margin, 14);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...LIGHT_PURPLE);
  doc.text("Daily Summary", margin, 20);
  doc.text(formatDateFull(today + "T00:00:00"), margin, 26);

  y = 46;

  // ─── Stat row ─────────────────────────────────────────
  const todayLogs = state.pointLogs.filter((l) => l.date.slice(0, 10) === today);
  const earned = todayLogs.filter((l) => l.type === "earned").reduce((s, l) => s + l.points, 0);
  const spent = todayLogs.filter((l) => l.type === "spent").reduce((s, l) => s + l.points, 0);
  const balance = state.totalPoints;

  const stats = [
    { label: "Points earned", value: `+${earned} C$` },
    { label: "Points spent", value: `-${spent} C$` },
    { label: "Balance", value: `${balance} C$` },
  ];

  const boxW = contentW / 3 - 3;
  stats.forEach((stat, i) => {
    const x = margin + i * (boxW + 4.5);
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(x, y, boxW, 18, 2, 2, "F");
    doc.setTextColor(140, 140, 140);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(stat.label, x + 4, y + 6);
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(stat.value, x + 4, y + 14);
  });

  y += 26;

  // ─── Mandal tasks grouped by sub-goal ─────────────────
  doc.setTextColor(...PURPLE);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Mandal-art — completed tasks", margin, y);
  y += 6;

  const hexToRgb = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b] as const;
  };

  let anyMandalTask = false;

  state.mandal.subGoals.forEach((sg) => {
    const done = sg.tasks.filter((t) => t.completed && t.text.trim());
    if (done.length === 0) return;
    anyMandalTask = true;

    // check page overflow
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    const rgb = hexToRgb(sg.color);
    doc.setFillColor(...rgb);
    doc.rect(margin, y, 3, done.length * 6 + 4, "F");

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(sg.title, margin + 6, y + 4);
    y += 7;

    done.forEach((t) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(60, 60, 60);
      doc.text(`✓  ${t.text}`, margin + 8, y);
      y += 5.5;
    });

    y += 3;
  });

  if (!anyMandalTask) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text("No mandal-art tasks completed today.", margin + 6, y);
    y += 8;
  }

  y += 4;

  // ─── To-do list ───────────────────────────────────────
  if (y > 250) { doc.addPage(); y = 20; }

  doc.setTextColor(...PURPLE);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("To-do — completed today", margin, y);
  y += 6;

  const doneTodos = state.todos.filter((t) => t.completed && t.text.trim());

  if (doneTodos.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text("No to-do items completed today.", margin + 6, y);
    y += 8;
  } else {
    doneTodos.forEach((t) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(60, 60, 60);
      const prefix = t.priority > 0 ? `[P${t.priority}] ` : "";
      doc.text(`✓  ${prefix}${t.text}`, margin + 6, y);
      y += 5.5;
    });
  }

  y += 8;

  // ─── Footer ───────────────────────────────────────────
  doc.setFillColor(...PURPLE);
  doc.rect(0, 287, pageW, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Planner", margin, 293);
  doc.text(new Date().toLocaleString(), pageW - margin, 293, { align: "right" });

  // ─── Save ─────────────────────────────────────────────
  doc.save(`planner-${today}.pdf`);
}